api_platform:
  mapping:
    paths: ["%kernel.project_dir%/src/Entity"]
  patch_formats:
    json: ["application/merge-patch+json"]
  swagger:
    versions: [3]
  # The title of the API.
  title: "CRM Api"
  collection:
    # The name of the query parameter to filter nullable results (with the ExistsFilter).
    # exists_parameter_name: "exists"

    # The default order of results. ASC or DSC
    order: "ASC"

    # The name of the query parameter to order results (with the OrderFilter).
    order_parameter_name: "order"

    pagination:
      # The default name of the parameter handling the page number.
      page_parameter_name: "page"

      # The name of the query parameter to enable or disable pagination.
      enabled_parameter_name: "pagination"

      # The name of the query parameter to set the number of items per page.
      items_per_page_parameter_name: "itemsPerPage"

      # The name of the query parameter to enable or disable the partial pagination.
      partial_parameter_name: "partial"
      # To enable or disable pagination for all resource collections by default.
      # Deprecated since 2.6 and will be removed in 3.0, use defaults.pagination_enabled instead.
      enabled: true
      # To allow partial pagination for all resource collections.
      # This improves performances by skipping the `COUNT` query.
      # Deprecated since 2.6 and will be removed in 3.0, use defaults.pagination_partial instead.
      # partial: false
      # To allow the client to enable or disable the pagination.
      # Deprecated since 2.6 and will be removed in 3.0, use defaults.pagination_client_enabled instead.
      client_enabled: true
      # To allow the client to set the number of items per page.
      # Deprecated since 2.6 and will be removed in 3.0, use defaults.pagination_client_items_per_page instead.
      # client_items_per_page: false
      # To allow the client to enable or disable the partial pagination.
      # Deprecated since 2.6 and will be removed in 3.0, use defaults.pagination_client_partial instead.
      #   client_partial: false
      # The default number of items per page.
      # Deprecated since 2.6 and will be removed in 3.0, use defaults.pagination_items_per_page instead.
      items_per_page: 30
    #   pagination_items_per_page: 30
    # The maximum number of items per page.
    # Deprecated since 2.6 and will be removed in 3.0, use defaults.pagination_maximum_items_per_page instead.
    # maximum_items_per_page: ~
